api_key: 567ac74d-92e2-483a-8ba7-e366a8fe7bea
base_url: https://ark.cn-beijing.volces.com/api/v3/images/generations
dev_mode: true
auto_save: false
save_dir: /Users/koali/Desktop/output
save_prefix: koali_
models:
  v5: doubao-seedream-5-0-260128
  v45: doubao-seedream-4-5-251126
  v4: doubao-seedream-4-0-250828
default:
  output_format: jpeg
  watermark: false
